### ISSUE TITLE
Corrupt Zip error when installing VSIX

### ISSUE THREAD

**Issue by ryanwaite** [radius-project/docs#459] opened 2023-01-04 00:00 UTC
Error: "Corrupt ZIP: end of central directory record signature not found"

Steps to reproduce on Mac:
1. Go to https://docs.radapp.dev/getting-started/install/
2. Click on link to download Bicep extension
3. After download completes, go to VS Code
4. Go to the Extensions Tab 
5. Click on the Ellipsis at the top of the Extensions pane and select "Install from VSIX..."
6. Choose the file you've downloaded

Results: Error described above in the lower right corner of VS Code. See Screenshot. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/3130479/210461045-4e525931-01f3-4606-9095-97285559b097.png">

[AB#5525](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5525)

**Comment by jkotalik** [comment] 2023-01-04 17:27
I just tried this myself on my M1 mac and didn't see this reproduce. Is anyone else able to repro this?

**Comment by AaronCrawfis** [comment] 2023-02-27 21:19
Closing as we're unable to reproduce. Please reopen if you hit this again

**Closed as not planned by AaronCrawfis** 2023-02-27 21:19 UTC
