### ISSUE TITLE
refresh properties tables in resource schema docs

### ISSUE THREAD

**Issue by emily-potyraj** [radius-project/docs#156] opened 2022-07-07 19:08 UTC
e.g. https://edge.radapp.dev/reference/resource-schema/core-schema/httproute/

We need to have a quick huddle here to make sure we have the most accurate info about what's returned to users.

**Comment by AaronCrawfis** [comment] 2022-07-25 21:58
Duplicate of #199

**Closed as not planned by AaronCrawfis** 2022-07-25 21:58 UTC
