### ISSUE TITLE
How-To: Define a portable resource

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#757] opened 2023-09-14 18:04 UTC
[AB#9374](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9374)

**Comment by Reshrahim** [comment] 2023-10-04 17:59
duplicate of https://github.com/radius-project/docs/issues/716

**Closed as not planned by Reshrahim** 2023-10-04 17:59 UTC
Labels: triaged, nov-release, how-to-guide
