### ISSUE TITLE
How-To: Share portable resources between applications

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/docs#758] opened 2023-09-14 18:05 UTC
[AB#9375](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9375)

**Comment by Reshrahim** [comment] 2023-10-04 18:01
duplicate of https://github.com/radius-project/docs/issues/715

**Closed as not planned by Reshrahim** 2023-10-04 18:01 UTC
Labels: triaged, how-to-guide
